#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""spell_fs_gui.py

Tkinter GUI wrapper for Spellcross *.FS tools:

- spell_extractfs.exe : unpack *.FS archives
- spell_makefs.exe    : pack a folder OR a *.lst (generated by spell_extractfs.exe)
                        back into a *.FS archive

Notes about packing tool (from ctime!cze by Stanislav Maslan):
- Usage: spellcross_makefs.exe source [archive_name] [-lh]
- Resulting *.FS is created in the folder where the EXE is launched (i.e. CWD).

Usage:
    python spell_fs_gui.py

Requirements:
    Python 3.x with tkinter (usually included on Windows).
"""

from __future__ import annotations

import threading
import queue
import subprocess
from pathlib import Path
import tkinter as tk
from tkinter import ttk, filedialog, messagebox

APP_TITLE = "Spellcross FS Tools (Extract + Pack GUI)"


def guess_exe_path(names: list[str]) -> Path | None:
    """Try to locate an exe next to this script or in CWD."""
    candidates: list[Path] = []

    try:
        here = Path(__file__).resolve().parent
        for n in names:
            candidates.append(here / n)
    except Exception:
        pass

    cwd = Path.cwd()
    for n in names:
        candidates.append(cwd / n)

    for p in candidates:
        if p.is_file():
            return p
    return None


class App(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title(APP_TITLE)
        self.minsize(920, 600)

        self.extract_exe_path = tk.StringVar(
            value=str(
                guess_exe_path([
                    "spell_extractfs.exe", "spell_extractfs.EXE",
                ])
                or "spell_extractfs.exe"
            )
        )

        self.make_exe_path = tk.StringVar(
            value=str(
                guess_exe_path([
                    "spell_makefs.exe", "spell_makefs.EXE",
                    "spellcross_makefs.exe", "spellcross_makefs.EXE",
                    "spell_makefs", "spellcross_makefs",
                ])
                or "spell_makefs.exe"
            )
        )

        self.extract_dest_dir = tk.StringVar(value=str(Path.cwd()))
        self.pack_dest_dir = tk.StringVar(value=str(Path.cwd()))

        self.make_subfolders = tk.BooleanVar(value=True)
        self.make_long_header = tk.BooleanVar(value=False)
        self.pack_archive_name = tk.StringVar(value="")

        self._work_thread: threading.Thread | None = None
        self._cancel_flag = threading.Event()
        self._log_q: "queue.Queue[str]" = queue.Queue()

        self._build_ui()
        self._poll_log()

    # ---------------- UI ----------------
    def _build_ui(self) -> None:
        pad = {"padx": 10, "pady": 6}

        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, **pad)

        tab_extract = ttk.Frame(nb)
        tab_pack = ttk.Frame(nb)
        nb.add(tab_extract, text="Extract (*.FS -> files)")
        nb.add(tab_pack, text="Pack (folder/*.lst -> *.FS)")

        self._build_extract_tab(tab_extract)
        self._build_pack_tab(tab_pack)

        # Bottom (shared): progress + log
        bot = ttk.Frame(self)
        bot.pack(fill="both", expand=False, **pad)

        self.progress = ttk.Progressbar(bot, mode="determinate")
        self.progress.pack(fill="x")

        ttk.Label(bot, text="Log:").pack(anchor="w", pady=(8, 0))
        self.txt = tk.Text(bot, height=12, wrap="word")
        self.txt.pack(fill="both", expand=True, pady=(4, 0))
        self.txt.configure(state="disabled")

        self._log("Ready. Choose tab Extract or Pack.")

    def _build_extract_tab(self, root: ttk.Frame) -> None:
        pad = {"padx": 10, "pady": 6}

        top = ttk.Frame(root)
        top.pack(fill="x", **pad)

        # EXE row
        exe_row = ttk.Frame(top)
        exe_row.pack(fill="x")
        ttk.Label(exe_row, text="Extractor exe:").pack(side="left")
        ttk.Entry(exe_row, textvariable=self.extract_exe_path).pack(side="left", fill="x", expand=True, padx=(8, 8))
        ttk.Button(exe_row, text="Browse…", command=self._browse_extract_exe).pack(side="left")

        # Destination row
        dst_row = ttk.Frame(top)
        dst_row.pack(fill="x", pady=(8, 0))
        ttk.Label(dst_row, text="Destination folder:").pack(side="left")
        ttk.Entry(dst_row, textvariable=self.extract_dest_dir).pack(side="left", fill="x", expand=True, padx=(8, 8))
        ttk.Button(dst_row, text="Browse…", command=self._browse_extract_dest).pack(side="left")

        # Options
        opt_row = ttk.Frame(top)
        opt_row.pack(fill="x", pady=(8, 0))
        ttk.Checkbutton(
            opt_row,
            text="Extract each archive into its own subfolder (recommended)",
            variable=self.make_subfolders
        ).pack(side="left")

        # Middle: list + buttons
        mid = ttk.Frame(root)
        mid.pack(fill="both", expand=True, **pad)

        left = ttk.Frame(mid)
        left.pack(side="left", fill="both", expand=True)

        ttk.Label(left, text="Archives to extract (*.FS):").pack(anchor="w")
        self.lb_extract = tk.Listbox(left, selectmode=tk.EXTENDED)
        self.lb_extract.pack(fill="both", expand=True, pady=(4, 0))
        self.lb_extract.bind("<Delete>", lambda e: self._remove_selected(self.lb_extract))

        right = ttk.Frame(mid)
        right.pack(side="left", fill="y", padx=(10, 0))

        ttk.Button(right, text="Add files…", command=self._add_extract_files).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Add folder…", command=self._add_extract_folder).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Remove selected", command=lambda: self._remove_selected(self.lb_extract)).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Clear list", command=lambda: self._clear_list(self.lb_extract)).pack(fill="x", pady=(0, 14))

        self.btn_extract_all = ttk.Button(right, text="Extract all", command=self._start_extract_all)
        self.btn_extract_all.pack(fill="x", pady=(0, 6))

        self.btn_extract_sel = ttk.Button(right, text="Extract selected", command=self._start_extract_selected)
        self.btn_extract_sel.pack(fill="x", pady=(0, 6))

        self.btn_cancel = ttk.Button(right, text="Cancel", command=self._cancel, state="disabled")
        self.btn_cancel.pack(fill="x", pady=(0, 6))

    def _build_pack_tab(self, root: ttk.Frame) -> None:
        pad = {"padx": 10, "pady": 6}

        top = ttk.Frame(root)
        top.pack(fill="x", **pad)

        # EXE row
        exe_row = ttk.Frame(top)
        exe_row.pack(fill="x")
        ttk.Label(exe_row, text="Packer exe:").pack(side="left")
        ttk.Entry(exe_row, textvariable=self.make_exe_path).pack(side="left", fill="x", expand=True, padx=(8, 8))
        ttk.Button(exe_row, text="Browse…", command=self._browse_make_exe).pack(side="left")

        # Output row
        out_row = ttk.Frame(top)
        out_row.pack(fill="x", pady=(8, 0))
        ttk.Label(out_row, text="Output folder (where *.FS will be created):").pack(side="left")
        ttk.Entry(out_row, textvariable=self.pack_dest_dir).pack(side="left", fill="x", expand=True, padx=(8, 8))
        ttk.Button(out_row, text="Browse…", command=self._browse_pack_dest).pack(side="left")

        # Options
        opt_row = ttk.Frame(top)
        opt_row.pack(fill="x", pady=(8, 0))
        ttk.Checkbutton(opt_row, text="-lh (long header)", variable=self.make_long_header).pack(side="left")

        # Archive name override (single item)
        name_row = ttk.Frame(top)
        name_row.pack(fill="x", pady=(8, 0))
        ttk.Label(name_row, text="Archive name override (optional; applied only when packing ONE item):").pack(side="left")
        ttk.Entry(name_row, textvariable=self.pack_archive_name).pack(side="left", fill="x", expand=True, padx=(8, 8))

        # Middle: list + buttons
        mid = ttk.Frame(root)
        mid.pack(fill="both", expand=True, **pad)

        left = ttk.Frame(mid)
        left.pack(side="left", fill="both", expand=True)

        ttk.Label(left, text="Sources to pack (folder OR *.lst):").pack(anchor="w")
        self.lb_pack = tk.Listbox(left, selectmode=tk.EXTENDED)
        self.lb_pack.pack(fill="both", expand=True, pady=(4, 0))
        self.lb_pack.bind("<Delete>", lambda e: self._remove_selected(self.lb_pack))

        right = ttk.Frame(mid)
        right.pack(side="left", fill="y", padx=(10, 0))

        ttk.Button(right, text="Add folder…", command=self._add_pack_folder).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Add .lst files…", command=self._add_pack_lst_files).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Add folder with .lst…", command=self._add_pack_folder_scan_lst).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Remove selected", command=lambda: self._remove_selected(self.lb_pack)).pack(fill="x", pady=(0, 6))
        ttk.Button(right, text="Clear list", command=lambda: self._clear_list(self.lb_pack)).pack(fill="x", pady=(0, 14))

        self.btn_pack_all = ttk.Button(right, text="Pack all", command=self._start_pack_all)
        self.btn_pack_all.pack(fill="x", pady=(0, 6))

        self.btn_pack_sel = ttk.Button(right, text="Pack selected", command=self._start_pack_selected)
        self.btn_pack_sel.pack(fill="x", pady=(0, 6))

        # Cancel button is shared (created in extract tab). Here we just add a note.
        ttk.Label(right, text="Tip: use Cancel in Extract tab\n(it cancels current operation too).", justify="left").pack(fill="x", pady=(10, 0))

    # ---------------- Generic helpers ----------------
    def _log(self, msg: str) -> None:
        self._log_q.put(msg)

    def _poll_log(self) -> None:
        try:
            while True:
                msg = self._log_q.get_nowait()
                self.txt.configure(state="normal")
                self.txt.insert("end", msg + "\n")
                self.txt.see("end")
                self.txt.configure(state="disabled")
        except queue.Empty:
            pass
        self.after(120, self._poll_log)

    def _set_running(self, running: bool) -> None:
        state_disabled = "disabled" if running else "normal"
        # Extract
        self.btn_extract_all.configure(state=state_disabled)
        self.btn_extract_sel.configure(state=state_disabled)
        # Pack
        self.btn_pack_all.configure(state=state_disabled)
        self.btn_pack_sel.configure(state=state_disabled)
        # Cancel
        self.btn_cancel.configure(state="normal" if running else "disabled")

    def _add_path(self, listbox: tk.Listbox, p: Path) -> None:
        p = p.resolve()
        existing = set(listbox.get(0, tk.END))
        if str(p) not in existing:
            listbox.insert(tk.END, str(p))

    def _remove_selected(self, listbox: tk.Listbox) -> None:
        sel = list(listbox.curselection())
        for idx in reversed(sel):
            listbox.delete(idx)

    def _clear_list(self, listbox: tk.Listbox) -> None:
        listbox.delete(0, tk.END)

    def _get_all_items(self, listbox: tk.Listbox) -> list[Path]:
        return [Path(x) for x in listbox.get(0, tk.END)]

    def _get_selected_items(self, listbox: tk.Listbox) -> list[Path]:
        sel = listbox.curselection()
        items = self._get_all_items(listbox)
        return [items[i] for i in sel] if sel else []

    def _update_progress(self, value: int) -> None:
        self.after(0, lambda: self.progress.configure(value=value))

    def _cancel(self) -> None:
        self._cancel_flag.set()
        self._log("Cancel requested (will stop after current item).")

    # ---------------- Browsers ----------------
    def _browse_extract_exe(self) -> None:
        p = filedialog.askopenfilename(
            title="Select spell_extractfs.exe",
            filetypes=[("Executable", "*.exe"), ("All files", "*.*")],
        )
        if p:
            self.extract_exe_path.set(p)

    def _browse_make_exe(self) -> None:
        p = filedialog.askopenfilename(
            title="Select spell_makefs.exe / spellcross_makefs.exe",
            filetypes=[("Executable", "*.exe"), ("All files", "*.*")],
        )
        if p:
            self.make_exe_path.set(p)

    def _browse_extract_dest(self) -> None:
        p = filedialog.askdirectory(title="Select destination folder")
        if p:
            self.extract_dest_dir.set(p)

    def _browse_pack_dest(self) -> None:
        p = filedialog.askdirectory(title="Select output folder (where *.FS will be created)")
        if p:
            self.pack_dest_dir.set(p)

    # ---------------- Extract tab actions ----------------
    def _add_extract_files(self) -> None:
        files = filedialog.askopenfilenames(
            title="Select *.FS archive(s)",
            filetypes=[("Spellcross FS archives", "*.FS *.fs"), ("All files", "*.*")],
        )
        for f in files:
            self._add_path(self.lb_extract, Path(f))

    def _add_extract_folder(self) -> None:
        folder = filedialog.askdirectory(title="Select folder with *.FS files")
        if not folder:
            return
        p = Path(folder)
        fs_files = sorted(list(p.glob("*.FS")) + list(p.glob("*.fs")))
        if not fs_files:
            messagebox.showinfo(APP_TITLE, "No *.FS files found in the selected folder.")
            return
        for f in fs_files:
            self._add_path(self.lb_extract, f)

    def _validate_extract(self) -> tuple[Path, Path] | None:
        exe = Path(self.extract_exe_path.get()).expanduser()
        if not exe.is_file():
            messagebox.showerror(APP_TITLE, f"Extractor not found:\n{exe}")
            return None
        dest = Path(self.extract_dest_dir.get()).expanduser()
        try:
            dest.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            messagebox.showerror(APP_TITLE, f"Cannot create destination folder:\n{dest}\n\n{e}")
            return None
        return exe, dest

    def _start_extract_all(self) -> None:
        items = self._get_all_items(self.lb_extract)
        if not items:
            messagebox.showinfo(APP_TITLE, "Add at least one *.FS file first.")
            return
        self._start_worker_extract(items)

    def _start_extract_selected(self) -> None:
        items = self._get_selected_items(self.lb_extract)
        if not items:
            messagebox.showinfo(APP_TITLE, "Select one or more items in the list.")
            return
        self._start_worker_extract(items)

    def _start_worker_extract(self, items: list[Path]) -> None:
        v = self._validate_extract()
        if not v:
            return
        exe, dest = v
        if self._work_thread and self._work_thread.is_alive():
            messagebox.showwarning(APP_TITLE, "An operation is already running.")
            return

        self._cancel_flag.clear()
        self._set_running(True)
        self.progress.configure(maximum=max(1, len(items)))
        self.progress.configure(value=0)

        def run() -> None:
            ok = 0
            fail = 0
            for i, fs_path in enumerate(items, start=1):
                if self._cancel_flag.is_set():
                    self._log("Canceled.")
                    break

                fs_path = fs_path.expanduser()
                if not fs_path.is_file():
                    self._log(f"[{i}/{len(items)}] SKIP (missing): {fs_path}")
                    fail += 1
                    self._update_progress(i)
                    continue

                out_dir = dest
                if self.make_subfolders.get():
                    stem = fs_path.stem
                    if stem.lower() != "data":
                        out_dir = dest / stem
                    try:
                        out_dir.mkdir(parents=True, exist_ok=True)
                    except Exception as e:
                        self._log(f"[{i}/{len(items)}] FAIL create folder {out_dir}: {e}")
                        fail += 1
                        self._update_progress(i)
                        continue

                self._log(f"[{i}/{len(items)}] Extracting: {fs_path.name} -> {out_dir}")
                try:
                    proc = subprocess.run(
                        [str(exe), str(fs_path)],
                        cwd=str(out_dir),
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        text=True,
                        errors="replace",
                    )
                    if proc.stdout.strip():
                        for line in proc.stdout.splitlines():
                            self._log("    " + line)
                    if proc.returncode == 0:
                        ok += 1
                        self._log("    OK")
                    else:
                        fail += 1
                        self._log(f"    FAIL (exit code {proc.returncode})")
                except FileNotFoundError:
                    fail += 1
                    self._log(f"    FAIL: extractor not found: {exe}")
                    break
                except Exception as e:
                    fail += 1
                    self._log(f"    FAIL: {e}")

                self._update_progress(i)

            self._log(f"Done (Extract). Success: {ok}, Failed: {fail}.")
            self.after(0, lambda: self._set_running(False))

        self._work_thread = threading.Thread(target=run, daemon=True)
        self._work_thread.start()

    # ---------------- Pack tab actions ----------------
    def _add_pack_folder(self) -> None:
        folder = filedialog.askdirectory(title="Select a folder to pack into *.FS")
        if not folder:
            return
        self._add_path(self.lb_pack, Path(folder))

    def _add_pack_lst_files(self) -> None:
        files = filedialog.askopenfilenames(
            title="Select *.lst file(s) created by spell_extractfs.exe",
            filetypes=[("List files", "*.lst"), ("All files", "*.*")],
        )
        for f in files:
            self._add_path(self.lb_pack, Path(f))

    def _add_pack_folder_scan_lst(self) -> None:
        folder = filedialog.askdirectory(title="Select folder; add all *.lst inside")
        if not folder:
            return
        p = Path(folder)
        lst_files = sorted(list(p.glob("*.lst")) + list(p.glob("*.LST")))
        if not lst_files:
            messagebox.showinfo(APP_TITLE, "No *.lst files found in the selected folder.")
            return
        for f in lst_files:
            self._add_path(self.lb_pack, f)

    def _validate_pack(self) -> tuple[Path, Path] | None:
        exe = Path(self.make_exe_path.get()).expanduser()
        if not exe.is_file():
            messagebox.showerror(APP_TITLE, f"Packer not found:\n{exe}")
            return None
        out_dir = Path(self.pack_dest_dir.get()).expanduser()
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            messagebox.showerror(APP_TITLE, f"Cannot create output folder:\n{out_dir}\n\n{e}")
            return None
        return exe, out_dir

    def _start_pack_all(self) -> None:
        items = self._get_all_items(self.lb_pack)
        if not items:
            messagebox.showinfo(APP_TITLE, "Add at least one source (folder or *.lst) first.")
            return
        self._start_worker_pack(items)

    def _start_pack_selected(self) -> None:
        items = self._get_selected_items(self.lb_pack)
        if not items:
            messagebox.showinfo(APP_TITLE, "Select one or more items in the list.")
            return
        self._start_worker_pack(items)

    def _start_worker_pack(self, items: list[Path]) -> None:
        v = self._validate_pack()
        if not v:
            return
        exe, out_dir = v
        if self._work_thread and self._work_thread.is_alive():
            messagebox.showwarning(APP_TITLE, "An operation is already running.")
            return

        self._cancel_flag.clear()
        self._set_running(True)
        self.progress.configure(maximum=max(1, len(items)))
        self.progress.configure(value=0)

        # archive name override only makes sense when packing exactly one item
        archive_override = self.pack_archive_name.get().strip()
        use_override = bool(archive_override) and (len(items) == 1)
        if archive_override and not use_override:
            self._log("NOTE: Archive name override is set, but you are packing multiple items -> ignoring override.")

        def run() -> None:
            ok = 0
            fail = 0
            for i, src in enumerate(items, start=1):
                if self._cancel_flag.is_set():
                    self._log("Canceled.")
                    break

                src = src.expanduser()
                if not src.exists():
                    self._log(f"[{i}/{len(items)}] SKIP (missing): {src}")
                    fail += 1
                    self._update_progress(i)
                    continue

                cmd = [str(exe), str(src)]
                if use_override:
                    cmd.append(archive_override)
                if self.make_long_header.get():
                    cmd.append("-lh")

                self._log(f"[{i}/{len(items)}] Packing: {src} -> {out_dir}")
                self._log("    CMD: " + " ".join(cmd))
                try:
                    proc = subprocess.run(
                        cmd,
                        cwd=str(out_dir),
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        text=True,
                        errors="replace",
                    )
                    if proc.stdout.strip():
                        for line in proc.stdout.splitlines():
                            self._log("    " + line)
                    if proc.returncode == 0:
                        ok += 1
                        self._log("    OK")
                    else:
                        fail += 1
                        self._log(f"    FAIL (exit code {proc.returncode})")
                except FileNotFoundError:
                    fail += 1
                    self._log(f"    FAIL: packer not found: {exe}")
                    break
                except Exception as e:
                    fail += 1
                    self._log(f"    FAIL: {e}")

                self._update_progress(i)

            self._log(f"Done (Pack). Success: {ok}, Failed: {fail}.")
            self.after(0, lambda: self._set_running(False))

        self._work_thread = threading.Thread(target=run, daemon=True)
        self._work_thread.start()


def main() -> int:
    try:
        app = App()
        app.mainloop()
        return 0
    except KeyboardInterrupt:
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
